version: '3.8'

services:
  app:
    image: dunglas/frankenphp:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
    environment:
      - FRANKENPHP_CONFIG=worker /app/public/index.php
      - SERVER_NAME=localhost
      - APP_ENV=dev
      - COMPOSER_ALLOW_SUPERUSER=1
    command: sh -c "cd /app && composer install && php artisan key:generate && php-fpm"