services:
  - type: web
    name: weather-api
    env: php
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          name: weather-api
          type: web
          property: url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: weather-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: weather-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: weather-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: weather-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: weather-db
          property: password
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: cookie
      - key: LOG_CHANNEL
        value: stack

databases:
  - name: weather-db
    plan: starter