databases:
  - name: laravel_db
    plan: free
    databaseName: laravel_db
    user: laravel_user

services:
  - type: web
    name: laravel-api
    plan: free
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: laravel_db
          property: connectionString
