services:
  - type: web
    name: weather-app-backend
    env: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    envVars:
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: cookie
    healthCheckPath: /api/health
